### PR TITLE
support multi install targets

### PR DESCRIPTION
**Pull request by ar90n**
This PR is aimed to support that install command accepts a list.(https://github.com/LoopPerfect/buckaroo/issues/51)

The output of running this pull request is the following.
It accepts multi install targets as list.

    $buckaroo install eigen/eigen ar90n/msgpack11  0.0.7
    Adding dependency on eigen/eigen,ar90n/msgpack11@0.0.7...
    Done.
    Installing dependencies...
    Installing eigen/eigen@3.2.9...
    Installing ar90n/msgpack11@0.0.7...
    Success!

Unfortunately, I am not familiar with Java.
So it may have a lot of undesirable codes.
If so, please tell me them.
I'll fix it promptly.

### CODE REVIEW

**Comment by nikhedonia** [comment]
Looks good!
Small thing is bothering me though:

```
buckaroo install google/gtest google/gtest

throws:
Uh oh!
Multiple entries with same key: google/gtest=Optional.empty and google/gtest=Optional.empty
line 1, column 34
```

It would be nice if it would work even if we have duplicates in the list.

**Comment by njlr** [comment]
+1 for filtering out duplicates. 

These should be equivalent: 

```bash=
buckaroo install google/gtest google/gtest
buckaroo install google/gtest
```

**Comment by ar90n** [comment]
Thanks for reviewing and comments.
I forgot to take them into account.
I agree with your idea.
I start to modify my PR.
Please give me some time.

**Comment by ar90n** [comment]
I added distinct operation to remove duplicates.
As a result, it treats the following two as equivalent.

    buckaroo install google/gtest google/gtest
    buckaroo install google/gtest

But there is still issue.
For example, the following case claim exceptions.

    buckaroo install google/gtest google/gtest 1.8.0
    Uh oh!
    Multiple entries with same key: google/gtest=Optional[ExactSemanticVersion{semanticVersions=[1.8.0]}] and google/gtest=Optional.empty
    line 1, column 40
  
I think it should be equivalent to the following.

    buckaroo install google/gtest 1.8.0

I think this issue can be regarded as  https://github.com/LoopPerfect/buckaroo/issues/10 case.
So, if it is ok, I want to solve this issue in https://github.com/LoopPerfect/buckaroo/issues/10 by passing duplicate targets to resolveDependency and calculating  union of their SemanticVersionRequirement.

**Comment by njlr** [comment]
I think the current solution is good for now. 

If the user enters two different version requirements it was probably a mistake on their part. 

```bash=
buckaroo install google/gtest google/gtest 1.8.0
```

I have implemented https://github.com/LoopPerfect/buckaroo/issues/10 (forgot to assign myself) in the https://github.com/LoopPerfect/buckaroo/tree/release/1.2.0 branch. The code in that branch is a bit of a mess at the moment, so I would not recommend building off of it. 

Thanks again!

**Comment by ar90n** [comment]
Thanks for your work and comment.
I understand the current status of buckaroo development.

I want to continue to contribute to this project.
Thus, I have one question.
Is it correct that I selected the master branch as the target branch of PR ?

**Comment by njlr** [comment]
Yes, master is considered the current release and should be the target for PRs.


On 3 Jun 2017, at 13:58, Masahiro Wada <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your work and comment.
I understand the current status of buckaroo development.

I want to continue to contribute to this project.
Thus, I have one question.
Is it correct that I selected the master branch as the target branch of PR ?

**Comment by ar90n** [comment]
Thanks. 
I got it.

**Pull request merged**
